---
- name: Converge
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Include ollama role"
      ansible.builtin.include_role:
        name: "ollama"
      vars:
        # Simuler l'installation sans télécharger le modèle complet
        skip_model_download: true 